### ISSUE TITLE
Adjust simple-monitor to zeebe 0.4.0

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe-simple-monitor#11]
- [x] adjust simple-monitor to use Zeebe version 0.4.0
- [x] create new release for simple-monitor

**Comment by saig0** [comment]
I adjusted the client version and tested it. It works when the default-topic is created. 

@menski , please set up a job in your CI to build the release. Thanks!

**Comment by menski** [comment]
I released version 0.1.1 https://github.com/zeebe-io/zeebe-simple-monitor/releases/tag/0.1.1
