### ISSUE TITLE
docker/run - mvn: command not found

### ISSUE THREAD

**Issue by IamManifold** [zeebe-io/zeebe-simple-monitor#116]
Looking to launch the monitor and receiving an error when it tries to do a clean install.

```
$ docker/run
No stopped containers
No stopped containers
Use hazelcast exporter version 0.7.0
Pulling zeebe   ... done
Pulling monitor ... done
Building project
docker/run: line 31: mvn: command not found
```

Line 30-31

> echo "Building project"
> mvn clean install

**Comment by Zelldon** [comment]
You need mvn and java to build the project.

**Comment by saig0** [comment]
Hi @IamManifold,

I replaced the existing docker-related files. The docker image is now built with the maven-jib-plugin (that is triggered on releasing a new version). For a local setup, the repo contains a docker-compose file. It starts the broker with the Hazelcast exporter and the simple monitor. Please have a look: https://github.com/zeebe-io/zeebe-simple-monitor#docker 

Maven is used to download and copy the Hazelcast exporter JAR. If Maven is not available then this step can also be done manually. The rest should still work.
