### ISSUE TITLE
split in starter and application

### ISSUE THREAD

**Issue by jangalinski** [zeebe-io/zeebe-simple-monitor#15]
when running a spring-zeebe application, I would like to integrate this via starter into my app instead of running an additional app. (see camunda-bpm-spring-boot-web starter).

This requires:

- webjar lib for resources
- sb starter lib for backend

application uses both libs

**Comment by saig0** [comment]
@jangalinski do you want to work on this?

**Comment by jangalinski** [comment]
I am quite busy right now, but I'll have a look, should not be too difficult.

**Comment by berndruecker** [comment]
Keep in mind that the simple monitor should be a simple monitor - I personally would't add it to any production app anyway ;-)
