### ISSUE TITLE
Incidents tab: Large Objects may not be used in auto-commit mode (PostgreSQL)

### ISSUE THREAD

**Issue by iamtakingiteasy** [zeebe-io/zeebe-simple-monitor#158]
Followup to #79 

Using postgresql as persistent database works with workflows and instances now, but same error still happens on incidents tab.

Apparently `@Transactional` annotation is missing on https://github.com/zeebe-io/zeebe-simple-monitor/blob/master/src/main/java/io/zeebe/monitor/rest/ViewController.java#L640

**Comment by saig0** [comment]
Thank you for reporting and immediately fixing it :tada:
