### ISSUE TITLE
zeebe-simple-monitor on kubernetes

### ISSUE THREAD

**Issue by SujataKale97** [zeebe-io/zeebe-simple-monitor#164]
Hello 
I want to deploy this zeebe-simple-monitor on kubernetes environment. Is there any official helm chart available or any deployment files? If so please share it.

I want guidance on how to deploy zeebe-simple-monitor on kubernetes.

**Comment by saig0** [comment]
Hi @SujataKale97,

I'm not aware of any helm chart that you can use. This repository contains only `docker-compose` files.

Do you have any general questions about the usage or configuration?
