### ISSUE TITLE
Adjust to Zeebe 0.10.0 deployment changes

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe-simple-monitor#17]
With Zeebe 0.9.0 the deployment changed that it is not distributed to every partition but keep globally on the system topic. That's why simple monitor now is not able to show any XML diagrams. These have now be fetched from the system topic and will not be part of a topic subscription on the topic itself.

For reference: https://github.com/zeebe-io/zeebe/commit/9e57514f5e540e77f6b4bd7f0264d056db965eff

**Comment by felix-mueller** [comment]
@menski is this something I could take over?

**Comment by menski** [comment]
@felix-mueller Feel free to give it a try. It probably is a little bit bigger change as its not part of the subscription anymore.

**Comment by saig0** [comment]
With Zeebe version 0.9.0, there is no way to get all deployed workflows. You can only fetch one workflow by key. So it's maybe not possible to port the monitor to this version.

**Comment by menski** [comment]
We probably have to wait for the workflow repository API which we should add to Zeebe 0.10.0 (https://github.com/zeebe-io/zeebe/issues/853).

**Comment by saig0** [comment]
Done
