### ISSUE TITLE
When process is killed - records get read again

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe-simple-monitor#19]
If you do a hard kill of the monitor (e.g. Eclipse Stop Button) the subscriptions to Zeebe are not cleanly closed and the last read offset is not committed. In this case some records are re-read on the next startup.

This will cause duplicate entry exceptions when querying mongo!

**Comment by berndruecker** [comment]
Doesn't make much sense to five into this at the moment as the topic subscription mechanism is currently under refactoring in Zeebe.

**Comment by saig0** [comment]
This is solved by porting the monitor to the exporter API #22.
