### ISSUE TITLE
Migrate simple monitor to use an Zeebe exporter

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe-simple-monitor#21]
At the moment the simple monitor use a topic subscription to import events from Zeebe. As topic subscriptions are deprecated the simple monitor should use a Zeebe exporter to retrieve the events.

There are currently two solutions discussed:
1. Creating a MongoDB exporter zeebe-io/zeebe#1331
2. Migrating the simple monitor to use a relation database over JDBC for example

If we continue with option 2 the search records feature might not work anymore. Which could be replaced by using kibana + elasticsearch exporter. 

With the JDBC approach we could support simple dev/demo setups (i.e. filebased sqlite database) and cluster setups (i.e. dedicated MySQL/Postgres).

**Comment by npepinpe** [comment]
:+1: for sqlite. I think we can approximate the JSON path queries using the JSON1 extension, so I don't see any specific advantage of using MongoDB.
