### ISSUE TITLE
Possible issue with spring context path

### ISSUE THREAD

**Issue by illpillow** [zeebe-io/zeebe-simple-monitor#219]
Hi there,
I was playing around with zeebe and possible monitoring solutions and found this project promising for development purposes. I was able to launch the spring boot service successfully, however, the UI looked rather broken. My investigation showed that the UI tried to load scripts from addresses like `//webjar` and `//js` which are obviously not fully qualified hosts, but valid links to external locations. This is due to the default configuration for the spring context path `/` which is translated to `//`. If I change it to something different like `/monitor` or an empty string, the UI just works fine on the given context root. I wonder if nobody else had this problem before as I did not find a related issue to it or if I missed something.

Reference: https://github.com/zeebe-io/zeebe-simple-monitor/blob/28ff8ad3d5c9c37bc802c0d4eac3a6a8ab3ae0f5/src/main/resources/application.yaml#L39

**Comment by jwulf** [comment]
Yes, I observe this also - I just update zeebe-docker-compose to use the 0.20.0 docker hub image, and CSS and JS are broken and do not load. In the HTML source, they are referenced as `//filename.css`, which gets interpreted as a domain.

**Comment by jwulf** [comment]
The cause is here: https://github.com/zeebe-io/zeebe-simple-monitor/blob/master/src/main/resources/templates/layout/header.html#L11

"Not requiring the trailing /" on the context works in all cases except when you set the context to "/".

**Comment by jwulf** [comment]
I set `context-path: ` (nothing) by mounting an application.yaml to the root directory of the docker image, and it works.

**Comment by illpillow** [comment]
Exactly. Are you going to correct it or shall I create a PR for it?

**Comment by jwulf** [comment]
PRs are always welcome. @saig0 is the maintainer.
