### ISSUE TITLE
JDBC URL should be configurable via Environment Variable

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe-simple-monitor#24]
It should be possible to configure the JDBC URL for the H2 connection via Environment variable. This would allow to startup H2 as separate instance and connect to it. This is important for scenarios where you want to restart every component independently

**Comment by saig0** [comment]
Hi @berndruecker ,

do you mean that you want to configure the URL of the exporter via environment variables?
In the web-app, it's already possible by using Spring Boot.

**Comment by berndruecker** [comment]
Yes

Sent from a mobile device.
________________________________
