### ISSUE TITLE
Exception on missing column in simple monitor

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe-simple-monitor#37]
When I start the broker 0.14.0 with the exporter enabled and then start simple monitor I get:

Schema-validation: missing column [created_] in table [incident]
--
2018-12-12 10:42:20.680 ERROR 9172 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing column [created_] in table [incident]

**Comment by saig0** [comment]
Did you start a previous version (0.7.0 or 0.8.0) of the exporter before? 

Currently, the exporter has no database update mechanism. So the table is not updated if you start a new version. You need to update the database manually or remove it ;)

**Comment by berndruecker** [comment]
that might be - I will double check

**Comment by berndruecker** [comment]
Yeah - that was the problem
