### ISSUE TITLE
spring.jpa.hibernate.ddl-auto should be update

### ISSUE THREAD

**Issue by aximo** [zeebe-io/zeebe-simple-monitor#44]
i down zeebe-simple-monitor-app-0.10.0.jar and run via
```
java -jar  zeebe-simple-monitor-app-0.10.0.jar
```
however,exception is happen:
```
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [activity_instance]
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateTable(AbstractSchemaValidator.java:121) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.tool.schema.internal.GroupedSchemaValidatorImpl.validateTables(GroupedSchemaValidatorImpl.java:42) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
```
i found that config in application.properties file is:
```
spring.jpa.hibernate.ddl-auto=validate
```

i think use 'update' is more reasonable

**Comment by Zelldon** [comment]
Hey,

thanks for the report.

Do you followed the setup guide? You need a running broker with a configured simple monitor exporter inside.

Or have you used an earlier version of Zeebe (and the simple monitor)? If so, then please make sure that you delete the h2 db in your home folder, befor restarting or start a new version. Currently we do not support update scripts for migrating to new versions. Also make sure that the latest exporter is added to the zeebe lib folder (please remove the old exporter jar).

Hope that helps.

Greets 
Chris

**Comment by aximo** [comment]
i am new one about zeebe and i miss the README.md, I just read the docs.zeebe.io,however it has no detail about run/config monitor.　now i get it work successfully.

btw,interesting and simple open-source. I notice you using template support by spring boot, maybe pure frontend is a another choice

**Comment by saig0** [comment]
Thank you for your feedback. Currently, we have no advanced frontend dev as maintainer. So we go with server-side rendering 😉
