### ISSUE TITLE
missing spring dependency ?

### ISSUE THREAD

**Issue by cmek** [zeebe-io/zeebe-simple-monitor#46]
running the monitor on Ubuntu 18.04LTS with openjdk-11-jre-headless:amd64         10.0.2+13-1ubuntu0.18.04.4 results in the following error:

[..]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-01-04 17:03:51.703 ERROR 4697 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
[..]

Adding this dependency to app/pom.xml:

 <dependency>
   <groupId>javax.xml.bind</groupId>
   <artifactId>jaxb-api</artifactId>
   <version>2.3.0</version>
 </dependency>

fixes the issue for me but I'm not a java person so please advise if there's a better solution for this.

**Comment by saig0** [comment]
Thank you for raising this up. I think this is related to Java 11. I didn't test it with Java 11 yet, only 8. In order to make it compatible we need to upgrade the Spring Boot version to 2.1.1.

**Comment by cmek** [comment]
not sure why I didn't think about trying Java 8 :) It works perfectly fine after switching to that version.

apparently it's a known issue with Spring Boot and Java versions >= 10. However, with that dependency added everything works perfectly fine with Java 11, at least with my limited testing so far.

**Comment by saig0** [comment]
I migrated to Spring Boot 2.1.2 (696cf902d03a51f37ebc86f4e12af357455d8e2f). This should fix the issue with Spring 11.
