### ISSUE TITLE
Migrate to Zeebe 0.15.0

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe-simple-monitor#54]
With Zeebe 0.15.0, the lifecycle of the events has changed. We need to adopt the changed in order to show the correct state of the instance.

**Comment by menski** [comment]
Probably interesting changes
- https://github.com/zeebe-io/zeebe/pull/1746
- https://github.com/zeebe-io/zeebe/pull/1966
- https://github.com/zeebe-io/zeebe/pull/1995
