### ISSUE TITLE
Deployment key from Java is +1

### ISSUE THREAD

**Issue by marc4gov** [zeebe-io/zeebe-simple-monitor#56]
When I deploy a workflow model from a Java client, I get an incremented key nr with respect to what is seen in the monitor

<img width="736" alt="schermafbeelding 2019-02-13 om 12 22 13" src="https://user-images.githubusercontent.com/9572139/52708299-1cff5a80-2f8a-11e9-924e-79494eeaf2ab.png">
<img width="544" alt="schermafbeelding 2019-02-13 om 12 21 46" src="https://user-images.githubusercontent.com/9572139/52708301-1cff5a80-2f8a-11e9-86c5-ae22e539a146.png">

**Comment by menski** [comment]
The deployment key is the unique identifier of the whole deployment. As a deployment can contain multiple workflows every workflow is assigned another unique key. See the `deploymentEvent.getWorkflows()` for the list of deployed workflows. These keys are what you see in the monitor. Does this answer your question?

**Comment by marc4gov** [comment]
I guess what you're saying is correct, when I run the DeploymentViewer, I get the same keys as in the monitor. The issue is when deploying a workflow from a Java client, I get a different key (exactly the key nr + 1) than listed in the monitor and with the DeploymentViewer. It's a minor issue, but confusing...
