### ISSUE TITLE
Docker build failure zeebee-simple-monitor-exporter.jar no such file or directory

### ISSUE THREAD

**Issue by xerxeArt** [zeebe-io/zeebe-simple-monitor#70]
Hello,
Running
`zeebe-simple-monitor-master\docker\local-config> docker build .`
gives the following error:
`Step 6/7 : COPY zeebe-simple-monitor-exporter.jar /usr/local/zeebe/lib/zeebe-simple-monitor-exporter.jar
ERROR: Service 'zeebe' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder035627378/zeebe-simple-monitor-exporter.jar: no such file or directory`

All the previous steps in the Dockerfile work correctly.
Do I need to generate the jar file before running docker build?

Thanks,
Cristian

**Comment by xerxeArt** [comment]
Dowloaded the .jar from [here](https://github.com/zeebe-io/zeebe-simple-monitor/releases).
Now I'm getting something else:
`ERROR: for local-config_zeebe_1  Cannot start service zeebe: b'OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/host_mnt/d/git/Zeebe/zeebe-simple-monitor-master/docker/local-config/zeebe.cfg.toml\\\\\\" to rootfs \\\\\\"/var/lib/docker/overlay2/807499b414893b378af9e2daaa2d892b62b26c8e050245dafd10d1190b03887c/merged\\\\\\" at \\\\\\"/var/lib/docker/overlay2/807499b414893b378af9e2daaa2d892b62b26c8e050245dafd10d1190b03887c/merged/usr/local/zeebe/conf/zeebe.cfg.toml\\\\\\" caused \\\\\\"not a directory\\\\\\"\\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type'`

**Comment by johanhallberg79** [comment]
Hi,
Try to run the docker/run script instead. It will build the .jar file for you. See the readme "how to run" section and also consider the note about building in a container.

BR,
Johan

**Comment by xerxeArt** [comment]
Thanks @johanhallberg79 , I finally got it working.
Note that I am on windows, so the commands I had to run were:
`docker-compose -f docker/local-config/docker-compose.yml pull`
`docker run -it --rm --name maven-zeebe-simple-monitor -v D:\git\Zeebe\zeebe-simple-monitor-master:/usr/src/zeebe-simple-monitor -w /usr/src/zeebe-simple-monitor maven:3.3-jdk-8 mvn clean install`
Here note that after -v you must put the absolute path to the local directory
`cp exporter/target/zeebe-simple-monitor-exporter-*.jar docker/local-config/zeebe-simple-monitor-exporter.jar`
`cd docker/local-config/`
`docker build -t camunda/zeebe-simple-monitor:latest -f app/Dockerfile app`
`docker-compose up --build`
