### ISSUE TITLE
deployment issue

### ISSUE THREAD

**Issue by RaviGithub555** [zeebe-io/zeebe-simple-monitor#71]
Hi,
I couldn't able to deploy new instance manually from zeebe monitor gui, 
throwing error, time out. If anybody the answer please help me here, I am new in zeebe.

Thanks & Regards,
Ravi Kumar

**Comment by saig0** [comment]
Hi @RaviGithub555 ,

please provide more information to analyze the issue. What are the steps to reproduce it? Do you see any errors in the log file?

Best regards,
Philipp

**Comment by RaviGithub555** [comment]
Hi Saig0,
while deploy new bpmn i am getting time out erro

**Comment by saig0** [comment]
I'm sorry but this doesn't help to analyze the issue. 

There can be many reasons why you are getting a time out. It could be that there is something wrong with your Zeebe broker. So, it would be good to see if the broker is started correctly, or if there are any errors. Also, how do you start the broker + monitor?

**Comment by RaviGithub555** [comment]
Hi Saig0,
Sorry, 
i downloaded zeebe broker server, and zeebe moniter souce code, configure with local h2 db, while deploy getting time out error in debug mode, other wise no error getting but , after refresh no workflow shown into the scree.

**Comment by RaviGithub555** [comment]
Hi Philipp,

below issue i m getting,
2019-06-20 18:15:42.281  INFO 11060 --- [nio-8080-exec-1]
o.h.h.i.QueryTranslatorFactoryInitiator  : HHH000397: Using
ASTQueryTranslatorFactory
2019-06-20 18:15:50.565 ERROR 11060 --- [nio-8080-exec-3]
o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet
[dispatcherServlet] in context with path [] threw exception [Request
processing failed; nested exception is
io.zeebe.client.cmd.ClientStatusException: Unexpected error occurred during
the request processing] with root cause

io.grpc.StatusRuntimeException: INTERNAL: Unexpected error occurred during
the request processing
at io.grpc.Status.asRuntimeException(Status.java:530)
~[grpc-core-1.18.0.jar:1.18.0]
at
io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
~[grpc-stub-1.18.0.jar:1.18.0]
at
io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
~[grpc-core-1.18.0.jar:1.18.0]
at
io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
~[grpc-core-1.18.0.jar:1.18.0]
at
io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
~[grpc-core-1.18.0.jar:1.18.0]
at
io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:699)
~[grpc-core-1.18.0.jar:1.18.0]
at
io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
~[grpc-core-1.18.0.jar:1.18.0]
at
io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
~[grpc-core-1.18.0.jar:1.18.0]
at
io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
~[grpc-core-1.18.0.jar:1.18.0]
at
io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
~[grpc-core-1.18.0.jar:1.18.0]
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
~[grpc-core-1.18.0.jar:1.18.0]
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
~[grpc-core-1.18.0.jar:1.18.0]
at
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
~[grpc-core-1.18.0.jar:1.18.0]
at
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
~[grpc-core-1.18.0.jar:1.18.0]
at
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
~[grpc-core-1.18.0.jar:1.18.0]
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
~[grpc-core-1.18.0.jar:1.18.0]
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
~[grpc-core-1.18.0.jar:1.18.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
~[na:1.8.0_152]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
~[na:1.8.0_152]
at java.lang.Thread.run(Unknown Source) [na:1.8.0_152]

even i staring both zeebe broker and zeebe monitor together ,Please help me
here.
on ui i m getting below issue:-
Error: Unexpected error occurred during the request processing

**Comment by saig0** [comment]
Please share your BPMN.
Which version do you use?

**Comment by RaviGithub555** [comment]
Hi phillip,

Thanks for your support, I got the solution, now zeebe monitor is working
fine, hurry...

Thanks & Regards,
Ravi kumar,
+91 8892303142

**Comment by themichaelscott** [comment]
Ravi, you never posted what your solution was and now I'm seeing the same issue.  Do you remember what you did to fix it?
