### ISSUE TITLE
Multiple deployments of same workflow breaks workflow drill down

### ISSUE THREAD

**Issue by atul-kulkarni** [zeebe-io/zeebe-simple-monitor#72]
Multiple deployments lead to multiple entries on default workflow-list page:

![image](https://user-images.githubusercontent.com/52247379/60902401-d7f8ff00-a26f-11e9-95d6-a085a99c1de1.png)

And if clicked on one of the **Workflow Key**,  results into **Whitelabel Error Page**

![image](https://user-images.githubusercontent.com/52247379/60902267-a3854300-a26f-11e9-9d73-80a3279d8cd0.png)

Logs:

[error.log](https://github.com/zeebe-io/zeebe-simple-monitor/files/3373784/error.log)

**Comment by atul-kulkarni** [comment]
Pull request created for fix

**Comment by saig0** [comment]
Thank you for raising this up and providing a fix :+1: 

Currently, I'm working on the next version and changing a few things, for example, how the data are imported into the monitor. When I merge my changes then this issue should not occur anymore.

I would let the issue open until the changes are merged and then you can check if this issue still exists or not. Is this ok for you?

**Comment by atul-kulkarni** [comment]
Thanks for quick reply. Sure, if the PR raised has conflicting changes to your branch and your changes already fixing couple of issues mentioned above. Thanks.
