### ISSUE TITLE
Feature Request: Show Task Type in BPMN diagram

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe-simple-monitor#80]
It would be super-useful to be able to see the task type in the diagram.

**Comment by saig0** [comment]
I'm working on it ;-)

**Comment by saig0** [comment]
If you want to see also the job type of service tasks that are not activated yet then you could use the BPMN model. For example, read the BPMN when it is rendered with bpmn.io and add an overlay to all service tasks.
