### ISSUE TITLE
Verify the connector's configuration, identify and stop any process that's listening on port 8080, or configure this application to listen on another port.

### ISSUE THREAD

**Issue by mike7ang1rdz** [zeebe-io/zeebe-simple-monitor#83]
How can I change the port the simple monitor will be listening, I'm running operate on port 8080

`Verify the connector's configuration, identify and stop any process that's listening on port 8080, or configure this application to listen on another port.`

**Comment by saig0** [comment]
You can use the property/environment variable (Spring Boot value) `server.port` to change the port.

**Comment by mike7ang1rdz** [comment]
thank you

for future reference only...

`_>  java -jar zeebe-simple-monitor-app-0.16.0.jar --server.port=8081`

**Comment by Maxalash** [comment]
Where you added this

_> java -jar zeebe-simple-monitor-app-0.16.0.jar --server.port=8081

statement?
