### ISSUE TITLE
docker/run

### ISSUE THREAD

**Issue by BravoJuliett** [zeebe-io/zeebe-simple-monitor#87]
With fresh clone of project on mac os mojave 10.14.6 the docker/run command produces

```
No stopped containers
No stopped containers
sed: 1: "docker/local-config/Doc ...": extra characters at the end of d command
```

**Comment by Urumuqi** [comment]
I have the same problem, can anyone help ?

**Comment by Zelldon** [comment]
Seems that sed not propably work on Mac OS 
https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux

I will try to find a different solution thanks for reporting.

**Comment by BravoJuliett** [comment]
For mac change line 25 in docker/run to
`sed "s/HAZELCAST_EXPORTER_VERSION=.*/HAZELCAST_EXPORTER_VERSION=$HAZELCAST_VERSION/g" $DOCKER_FILE`

**Comment by sourabhjagtap95** [comment]
Please mention java version as v11 while installing.

**Comment by josefelipepc** [comment]
Hi, have a problem with Java, the image of alpine have java 1.8 and zeebe monitor require java 11. Is this problem happening to someone?

**Comment by bekbergenb** [comment]
Hi, got this problem when do docker/run
`Step 6/6 : COPY --from=downloader /tmp/zeebe-hazelcast-exporter-jar-with-dependencies.jar /usr/local/zeebe/lib/zeebe-hazelcast-exporter-jar-with-dependencies.jar
ERROR: Service 'zeebe' failed to build: COPY failed: stat /var/lib/docker/overlay2/2b36b2311bb2d689583b347beebc1bff39f3a7ea7e3b97e1a065177b99c07bcb/merged/tmp/zeebe-hazelcast-exporter-jar-with-dependencies.jar: no such file or directory`
Maybe exporter not download yet and not moved to /tmp folder

**Comment by PMarci** [comment]
I'm experiencing the same issue as @bekbergenb.

**Comment by PMarci** [comment]
I realised it's unrelated to the original issue here, so I opened a new one: #124

**Comment by saig0** [comment]
Hi all,

I replaced the existing docker-related files. The docker image is now built with the maven-jib-plugin (that is triggered on releasing a new version). For a local setup, the repo contains a docker-compose file. It starts the broker with the Hazelcast exporter and the simple monitor. Please have a look: https://github.com/zeebe-io/zeebe-simple-monitor#docker 

Does this work for you?
Do you need anything else?
